Company.web/Controllers/RoleController.cs
using Company.Data.Entities;
using Company.web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.web.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        public RoleManager<IdentityRole> _RoleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager , UserManager<ApplicationUser> userManager)
        {
            _RoleManager = roleManager;
            _userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            var roles = await _RoleManager.Roles.ToListAsync();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(IdentityRole role)
        {
            if (ModelState.IsValid) 
            {
                var result = await _RoleManager.CreateAsync(role);
                if (result.Succeeded) 
                {
                    return RedirectToAction("Index");
                }
            }
            return View(role);
        }

        public async Task<IActionResult> Details(string Id)
        {
            var role = await _RoleManager.FindByIdAsync(Id);
            if (role == null)
            {
                return NotFound();
            }

            var model = new RoleUpdateViewModel
            {
                Id = role.Id,
                Name = role.Name
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Update(string Id, RoleUpdateViewModel model)
        {
            if (Id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _RoleManager.FindByIdAsync(Id);
                    if (role == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        role.Name = model.Name;
                        role.NormalizedName = model.Name.ToUpper();

                        var result = await _RoleManager.UpdateAsync(role);
                        if (result.Succeeded)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                }
                catch (Exception ex)
                {
                    throw;
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var role = await _RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return NotFound();
                }
                var result = await _RoleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {

            }
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _RoleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }
            ViewBag.RoleId = roleId;
            var users = await _userManager.Users.ToListAsync();
            var usersInRole = new List<UserInRoleViewModel>();
            foreach (var user in users)
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;
                }
                else
                {
                    userInRole.IsSelected = false;
                }
                usersInRole.Add(userInRole);
            }
            return View(usersInRole);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId, List<UserInRoleViewModel> users)
        {
            var role = await _RoleManager.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                foreach(var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if (appUser is not null)
                    {
                        if(user.IsSelected && await _userManager.IsInRoleAsync(appUser , role.Name))
                        {
                            await _userManager.AddToRoleAsync(appUser , role.Name);
                        }else if (!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            return View(users);
        }

    }
}

Company.web/Controllers/UserController.cs
using AutoMapper.Configuration.Annotations;
using Company.Data.Entities;
using Company.Service.DTO;
using Company.web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.web.Controllers
{
    [Authorize(Roles ="Admin")]
	public class UserController : Controller
	{
		public UserManager<ApplicationUser> _UserManager;
        public UserController(UserManager<ApplicationUser> userManager)
        {
			_UserManager = userManager;
		}


		public async Task<IActionResult> Index(string searchInp)
		{
			List<ApplicationUser> users;
			if (string.IsNullOrEmpty(searchInp))
			{
				users = await _UserManager.Users.ToListAsync();
			}
			else
			{
				users = await _UserManager.Users.Where(u => u.NormalizedEmail.Trim().Contains(searchInp.ToUpper().Trim())).ToListAsync();	
			}
			return View(users);
		}


        public async Task<IActionResult> Details(string Id)
        {
            var user = await _UserManager.FindByIdAsync(Id);
            if (user == null)
            {
                return NotFound();
            }

            var model = new UserUpdateViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email
            };

            return View(model);
        }



        [HttpPost]
        [HttpPost]
        public async Task<IActionResult> Update(string Id, UserUpdateViewModel model)
        {
            if (Id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var user = await _UserManager.FindByIdAsync(Id);
                if (user == null)
                {
                    return NotFound();
                }

                user.UserName = model.UserName;
                user.NormalizedUserName = model.UserName.ToUpper();
                user.Email = model.Email;

                var result = await _UserManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
		{
			try
			{
				var user = await _UserManager.FindByIdAsync(id);
				if (user == null)
				{
					return NotFound();
				}
				var result = await _UserManager.DeleteAsync(user);

				if (result.Succeeded)
				{
					return RedirectToAction("Index");
				}
			}
			catch (Exception ex)
			{

			}
			return RedirectToAction("Index");
		}

    }
}

Company.web/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico" />

	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" type="text/css" href="~/fonts/iconic/css/material-design-iconic-font.min.css">
	
	<link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
	
	<link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
	
	<link rel="stylesheet" type="text/css" href="~/vendor/animsition/css/animsition.min.css">
	
	<link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
	
	<link rel="stylesheet" type="text/css" href="~/vendor/daterangepicker/daterangepicker.css">
	
	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">
	
</head>
<body>

	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				@RenderBody()
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

	
	<script src="~/js/jquery-3.2.1.min.js"></script>
	
	<script src="~/animsition/js/animsition.min.js"></script>
	
	<script src="~/js/popper.js"></script>
	<script src="~/js/bootstrap.min.js"></script>
	
	<script src="~/select2/select2.min.js"></script>
	
	<script src="~/daterangepicker/moment.min.js"></script>
	<script src="~/daterangepicker/daterangepicker.js"></script>
	
	<script src="~/countdowntime/countdowntime.js"></script>
	
	<script src="~/js/main.js"></script>

</body>
</html>

Company.web/Views/Shared/_ButtonsPartial.cshtml
@model int

@{
    string controller = ViewData["Controller"]?.ToString() ?? "Department"; // Default to Department if not provided
}

<td>
    <a asp-action="Details" asp-controller="@controller" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Delete" asp-controller="@controller" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Company.web/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {

                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        }

                            @if (signInManager.IsSignedIn(User))
                            { 
                                <li class="nav-item ms-auto">
                                    <a class="nav-link text-light btn btn-danger" asp-area="" asp-controller="Account" asp-action="LogOut">Logout</a>
                                </li>
                            }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Company.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>